### ISSUE TITLE
About Chinese Translation

### ISSUE THREAD

**Issue by MushroomEl** [Moffein/BlightedElites#4]
Hello author, I like this mod very much and am playing this mod with my friends. I made a Chinese translation and hope it can be adopted.
[MoffeinBlightedElites.txt](https://github.com/Moffein/BlightedElites/files/15489164/MoffeinBlightedElites.txt)
Should be placed in the zh-CN folder.
Thank you for your work.

**Comment by Moffein** [comment]
Thanks, adding this!
